### ISSUE TITLE
Command returning: No components found.

### ISSUE THREAD

**Issue by tokra** [tim-lo/getRTCHistory#1]
Script is not working for me and when I tried command:
`scm --show-alias n --show-uuid n list components -r "$REPO" --projectarea "$PROJECT" -u "$USER" -P "$PASS"`

it gives me: `No components found.`

I think we need to specify also stream somehow.

**Comment by tim-lo** [comment]
Thanks I'll take a look. Maybe the API's changed or something.

**Comment by tokra** [comment]
I made new version of script, and it works now. however i change it bit. so i might fork your repo and push it there

**Comment by tim-lo** [comment]
That'd be awesome, please do! 😄

**Comment by tokra** [comment]
;-)

**Comment by tokra** [comment]
Here is my fork https://github.com/to-kra/getRTCHistory

**Comment by tim-lo** [comment]
Good stuff! 👍
